apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
data:
  NODE_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
  CORS_ORIGIN: "*"
  RATE_LIMIT_WINDOW: "15"
  RATE_LIMIT_MAX_REQUESTS: "100" 